version: '3'

services:
  app:
    build:
      context: ./php
    container_name: app
    volumes:
      - ../:/var/www
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ..:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
